modLoader="javafml" 
loaderVersion="[45,)"
license="LGPL 3.0"
[[mods]]
modId="flowerseeds" 
version="${file.jarVersion}" 
displayName="Flower Seeds" 
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
updateJSONURL="https://forge.curseupdate.com/445955/flowerseeds"
logoFile="examplemod.png" #optional
credits=""
authors="Trhod177"
# The description text for the mod (multi line!) (#mandatory)
description='''
No longer do you need to spend several hours hunting large quantities of flowers.
'''

[[dependencies.flowerseeds]]
        modId="byg"
        mandatory=false
        versionRange="[*,)"
        ordering="AFTER"
        side="BOTH"

[[dependencies.flowerseeds]]
        modId="cyclic"
        mandatory=false
        versionRange="[*,)"
        ordering="AFTER"
        side="BOTH"

[[dependencies.flowerseeds]] #optional
    modId="forge" 
    mandatory=true
    versionRange="[45,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.flowerseeds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



